/**
 * Component Analytics — Test Configuration
 *
 * This configuration is used automatically when tests run (detected via
 * the JEST_WORKER_ID environment variable).  It provides explicit
 * component lists so that tests relying on TRACKED_COMPONENTS are
 * deterministic regardless of what the user's real config contains.
 *
 * @type {import("./scripts/lib/config-schema").StudioAnalysisConfig}
 */
module.exports = {
  codebases: [
    { name: "Studio", path: "./codebases/sanity" },
    { name: "Media Library", path: "./codebases/huey" },
    { name: "Canvas", path: "./codebases/canvas" },
  ],

  uiLibraries: [
    {
      name: "Sanity UI",
      importSources: ["@sanity/ui"],
      excludeSources: ["@sanity/ui/theme"],
      wrapperSources: ["ui-components"],

      components: [
        // ── Layout ────────────────────────────────────────────────
        "Box",
        "Container",
        "Flex",
        "Grid",
        "Inline",
        "Stack",

        // ── Interactive ───────────────────────────────────────────
        "Button",
        "Card",
        "Dialog",
        "Menu",
        "MenuButton",
        "MenuDivider",
        "MenuGroup",
        "MenuItem",
        "Popover",
        "Tab",
        "TabList",
        "TabPanel",
        "Tooltip",

        // ── Form ──────────────────────────────────────────────────
        "Autocomplete",
        "Checkbox",
        "Label",
        "Radio",
        "Select",
        "Switch",
        "TextArea",
        "TextInput",

        // ── Typography ────────────────────────────────────────────
        "Badge",
        "Code",
        "Heading",
        "KBD",
        "Text",

        // ── Feedback ──────────────────────────────────────────────
        "Spinner",
        "Toast",

        // ── Data Display ──────────────────────────────────────────
        "Avatar",
        "AvatarCounter",
        "AvatarStack",
        "Skeleton",
        "TextSkeleton",
        "Tree",
        "TreeItem",

        // ── Utility / Providers ───────────────────────────────────
        "BoundaryElementProvider",
        "ErrorBoundary",
        "Layer",
        "LayerProvider",
        "Portal",
        "PortalProvider",
        "ThemeColorProvider",
        "ThemeProvider",
        "TooltipDelayGroupProvider",
      ],
    },
    {
      name: "Sanity Icons",
      importSources: ["@sanity/icons"],
      excludeSources: [],

      components: [
        "AccessDeniedIcon",
        "ActivityIcon",
        "AddCircleIcon",
        "AddCommentIcon",
        "AddIcon",
        "ApiIcon",
        "ArchiveIcon",
        "ArrowDownIcon",
        "ArrowLeftIcon",
        "ArrowRightIcon",
        "ArrowTopRightIcon",
        "ArrowUpIcon",
        "BarChartIcon",
        "BasketIcon",
        "BellIcon",
        "BillIcon",
        "BinaryDocumentIcon",
        "BlockContentIcon",
        "BlockElementIcon",
        "BlockquoteIcon",
        "BoldIcon",
        "BoltIcon",
        "BookIcon",
        "BottleIcon",
        "BulbFilledIcon",
        "BulbOutlineIcon",
        "CalendarIcon",
        "CaseIcon",
        "ChartUpwardIcon",
        "CheckmarkCircleIcon",
        "CheckmarkIcon",
        "ChevronDownIcon",
        "ChevronLeftIcon",
        "ChevronRightIcon",
        "ChevronUpIcon",
        "CircleIcon",
        "ClipboardIcon",
        "ClipboardImageIcon",
        "ClockIcon",
        "CloseCircleIcon",
        "CloseIcon",
        "CodeBlockIcon",
        "CodeIcon",
        "CogIcon",
        "CollapseIcon",
        "ColorWheelIcon",
        "CommentIcon",
        "ComposeIcon",
        "ComposeSparklesIcon",
        "ConfettiIcon",
        "ControlsIcon",
        "CopyIcon",
        "CreditCardIcon",
        "CropIcon",
        "DashboardIcon",
        "DatabaseIcon",
        "DesktopIcon",
        "DocumentIcon",
        "DocumentRemoveIcon",
        "DocumentSheetIcon",
        "DocumentTextIcon",
        "DocumentVideoIcon",
        "DocumentWordIcon",
        "DocumentZipIcon",
        "DocumentsIcon",
        "DotIcon",
        "DoubleChevronDownIcon",
        "DoubleChevronLeftIcon",
        "DoubleChevronRightIcon",
        "DoubleChevronUpIcon",
        "DownloadIcon",
        "DragHandleIcon",
        "DropIcon",
        "EarthAmericasIcon",
        "EarthGlobeIcon",
        "EditIcon",
        "EllipsisHorizontalIcon",
        "EllipsisVerticalIcon",
        "EmailIcon",
        "EnvelopeIcon",
        "EqualIcon",
        "ErrorFilledIcon",
        "ErrorOutlineIcon",
        "ExpandIcon",
        "EyeClosedIcon",
        "EyeOpenIcon",
        "FilterIcon",
        "FolderIcon",
        "GenerateIcon",
        "GridIcon",
        "HashIcon",
        "HeartFilledIcon",
        "HeartIcon",
        "HelpCircleIcon",
        "HighlightIcon",
        "HomeIcon",
        "IceCreamIcon",
        "ImageIcon",
        "ImageRemoveIcon",
        "ImagesIcon",
        "InfoFilledIcon",
        "InfoOutlineIcon",
        "InlineElementIcon",
        "InlineIcon",
        "InsertAboveIcon",
        "InsertBelowIcon",
        "ItalicIcon",
        "JoystickIcon",
        "JsonIcon",
        "LaunchIcon",
        "LeaveIcon",
        "LemonIcon",
        "LinkIcon",
        "LinkRemovedIcon",
        "ListIcon",
        "LockIcon",
        "LogoJavascriptIcon",
        "LogoTypescriptIcon",
        "MarkerIcon",
        "MasterDetailIcon",
        "MenuIcon",
        "MicrophoneIcon",
        "MobileDeviceIcon",
        "MoonIcon",
        "NumberIcon",
        "OkHandIcon",
        "OrderedListIcon",
        "OlistIcon",
        "OverflowHorizontalIcon",
        "OverflowVerticalIcon",
        "PackageIcon",
        "PanelLeftIcon",
        "PanelRightIcon",
        "PauseIcon",
        "PinIcon",
        "PinFilledIcon",
        "PlayIcon",
        "PlugIcon",
        "PublishIcon",
        "ReadOnlyIcon",
        "RedoIcon",
        "RefreshIcon",
        "RemoveCircleIcon",
        "RemoveIcon",
        "ResetIcon",
        "RestoreIcon",
        "RetryIcon",
        "RevertIcon",
        "RobotIcon",
        "RocketIcon",
        "SchemaIcon",
        "SearchIcon",
        "SelectIcon",
        "ShareIcon",
        "SortIcon",
        "SparkleIcon",
        "SparklesIcon",
        "SpinnerIcon",
        "SplitHorizontalIcon",
        "SplitVerticalIcon",
        "SquareIcon",
        "StackCompactIcon",
        "StackIcon",
        "StarFilledIcon",
        "StarIcon",
        "StrikethroughIcon",
        "StringIcon",
        "SunIcon",
        "SyncIcon",
        "TabIcon",
        "TagIcon",
        "TerminalIcon",
        "TextIcon",
        "ThLargeIcon",
        "ThListIcon",
        "TiersIcon",
        "ToggleArrowRightIcon",
        "TokenIcon",
        "TransferIcon",
        "TranslateIcon",
        "TrashIcon",
        "TrendUpwardIcon",
        "TriangleOutlineIcon",
        "TruncateIcon",
        "UnderlineIcon",
        "UndoIcon",
        "UnknownIcon",
        "UnlockIcon",
        "UnpublishIcon",
        "UploadIcon",
        "UserIcon",
        "UsersIcon",
        "WarningFilledIcon",
        "WarningOutlineIcon",
        "WrenchIcon",
      ],
    },
  ],

  files: {
    pattern: "**/*.{tsx,jsx}",
    ignore: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/*.test.*",
      "**/*.spec.*",
      "**/__tests__/**",
      "**/*.stories.*",
    ],
  },

  otherUIPatterns: [
    "@radix-ui",
    "styled-components",
    "motion/react",
    "framer-motion",
  ],

  propCombos: [
    { component: "Text", props: ["weight", "size"] },
    { component: "Button", props: ["tone", "mode"] },
    { component: "Button", props: ["fontSize", "padding", "radius"] },
    { component: "Card", props: ["tone", "padding", "radius"] },
    { component: "Card", props: ["radius", "tone"] },
    { component: "Heading", props: ["size", "as"] },
  ],
};
